logging:
  level:
    org.springframework.web: WARN
    com.ote.test: INFO

server:
  port: 8081

spring:
  application:
    name: Client

remote:
  server:
    uri: http://localhost:8080
    activemq-uri: tcp://localhost:61616

